# Run tests
[tasks.test]
run = "pytest"
env = "uv"

# Build package
[tasks.build]
run = "uv build"

# Format source files
[tasks.format]
run = "ruff format ."
env = "uv"

# Run linter
[tasks.lint]
run = "ruff check ."
env = "uv"
