[template]
description = "pytest + ruff"
env = "uv"

# Run tests
[tasks.test]
run = "uvx pytest"

# Build package
[tasks.build]
run = "uv build"

# Format source files
[tasks.format]
run = "uvx ruff format ."

# Run linter
[tasks.lint]
run = "uvx ruff check ."
