[[snippets]]
name = "npm task"
description = "Task using npx"
content = """
[tasks.dev]
env = "npm"
run = "vite"
"""

[[snippets]]
name = "npm test"
description = "Run tests with vitest"
content = """
[tasks.test]
env = "npm"
run = "vitest run"
"""

[[snippets]]
name = "npm lint"
description = "Run eslint"
content = """
[tasks.lint]
env = "npm"
run = "eslint src/"
"""
